import type { Express } from "express";
import { authRouter } from "#server/routes/auth.js";
import { faucetRouter } from "#server/routes/faucet.js";
import { walletRouter } from "#server/routes/wallet.js";
import { miningRouter } from "#server/routes/mining.js";
import { shopRouter } from "#server/routes/shop.js";
import { inventoryRouter } from "#server/routes/inventory.js";
import { machinesRouter } from "#server/routes/machines.js";
import { racksRouter } from "#server/routes/racks.js";
import vaultRouter from "#server/routes/vault.js";
import { readEarnRouter } from "#server/routes/read-earn.js";
import { roomsRouter } from "#server/routes/rooms.js";
import { checkinRouter } from "#server/routes/checkin.js";
import { offerEventsRouter } from "#server/routes/offer-events.js";
import { miniPassRouter } from "#server/routes/mini-pass.js";
import { dailyTasksRouter } from "#server/routes/daily-tasks.js";
import { internalOfferwallRouter } from "#server/routes/internal-offerwall.js";
import { chatRouter } from "#server/routes/chat.js";
import { rankingRouter } from "#server/routes/ranking.js";
import { statsRouter } from "#server/routes/stats.js";
import { shortlinkRouter } from "#server/routes/shortlink.js";
import { youtubeRouter } from "#server/routes/youtube.js";
import { gamesRouter } from "#server/routes/games.js";
import { autoMiningGpuRouter } from "#server/routes/auto-mining-gpu.js";
import { sessionRouter } from "#server/routes/session.js";
import { notificationRouter } from "#server/routes/notification.js";
import { broadcastRouter } from "#server/routes/broadcast.js";
import { swapRouter } from "#server/routes/swap.js";
import supportRouter from "#server/routes/support.js";
import userRouter from "#server/routes/user.js";
import { publicSupportRouter } from "#server/modules/publicSupport/publicSupport.routes.js";
import { sidebarNavRouter } from "#server/routes/sidebar-nav.js";
import { rewardInboxRouter } from "#server/routes/reward-inbox.js";

export function mountUserApplicationApiRoutes(app: Express): void {
  app.use("/api/auth", authRouter);
  app.use("/api/faucet", faucetRouter);
  app.use("/api/wallet", walletRouter);
  app.use("/api/mining", miningRouter);
  app.use("/api/shop", shopRouter);
  app.use("/api/inventory", inventoryRouter);
  app.use("/api/machines", machinesRouter);
  app.use("/api/racks", racksRouter);
  app.use("/api/vault", vaultRouter);
  app.use("/api/read-earn", readEarnRouter);
  app.use("/api/rooms", roomsRouter);
  app.use("/api/checkin", checkinRouter);
  app.use("/api/offer-events", offerEventsRouter);
  app.use("/api/mini-pass", miniPassRouter);
  app.use("/api/daily-tasks", dailyTasksRouter);
  app.use("/api/internal-offerwall", internalOfferwallRouter);
  app.use("/api/chat", chatRouter);
  app.use("/api/ranking", rankingRouter);
  app.use("/api/stats", statsRouter);
  app.use("/api/shortlink", shortlinkRouter);
  app.use("/api/youtube", youtubeRouter);
  app.use("/api/games", gamesRouter);
  app.use("/api/auto-mining-gpu", autoMiningGpuRouter);
  app.use("/api/session", sessionRouter);
  app.use("/api/notifications", notificationRouter);
  app.use("/api/broadcast", broadcastRouter);
  app.use("/api/swap", swapRouter);
  app.use("/api/support", supportRouter);
  app.use("/api/user", userRouter);
  app.use("/api/sidebar", sidebarNavRouter);
  app.use("/api/reward-inbox", rewardInboxRouter);
  app.use("/api/public-support", publicSupportRouter);
}
