import type { Express } from "express";
import { authRouter } from "#server/modules/auth/index.js";
import { faucetRouter } from "#server/modules/faucet/index.js";
import { walletRouter } from "#server/modules/wallet/index.js";
import { miningRouter } from "#server/modules/mining/index.js";
import { shopRouter } from "#server/modules/shop/index.js";
import { inventoryRouter } from "#server/modules/inventory/index.js";
import { machinesRouter } from "#server/modules/machines/index.js";
import { racksRouter } from "#server/modules/racks/index.js";
import vaultRouter from "#server/modules/vault/index.js";
import { readEarnRouter } from "#server/modules/read-earn/index.js";
import { roomsRouter } from "#server/modules/rooms/index.js";
import { checkinRouter } from "#server/modules/checkin/index.js";
import { offerEventsRouter } from "#server/modules/offer-events/index.js";
import { miniPassRouter } from "#server/modules/mini-pass/index.js";
import { dailyTasksRouter } from "#server/modules/tasks/index.js";
import { internalOfferwallRouter } from "#server/modules/internal-offerwall/index.js";
import { chatRouter } from "#server/modules/chat/index.js";
import { rankingRouter } from "#server/modules/ranking/index.js";
import { statsRouter } from "#server/modules/stats/index.js";
import { shortlinkRouter } from "#server/modules/shortlinks/index.js";
import { youtubeRouter } from "#server/modules/youtube/index.js";
import { gamesRouter } from "#server/modules/games/index.js";
import { autoMiningGpuRouter } from "#server/modules/auto-mining/index.js";
import { sessionRouter } from "#server/modules/session/index.js";
import { notificationRouter } from "#server/modules/notifications/index.js";
import { broadcastRouter } from "#server/modules/broadcast/index.js";
import { swapRouter } from "#server/modules/swap/index.js";
import supportRouter from "#server/modules/support/index.js";
import { userRouter } from "#server/modules/users/index.js";
import { publicSupportRouter } from "#server/modules/publicSupport/publicSupport.routes.js";
import { sidebarNavRouter } from "#server/modules/sidebar-nav/index.js";
import { rewardInboxRouter } from "#server/modules/reward-inbox/index.js";
import { zeradsRouter } from "#server/modules/zerads/zerads.routes.js";
import { powerBoostRouter } from "#server/modules/powerBoost/powerBoost.routes.js";
import { socialRouter } from "#server/modules/social/social.routes.js";
import { tournamentsRouter } from "#server/modules/tournaments/index.js";
import { ptcRouter } from "#server/modules/ptc/ptc.routes.js";
import { partnerGamesRouter } from "#server/modules/partnerGames/index.js";
import { burnEventsRouter } from "#server/modules/burnEvents/index.js";
import { energyTaxRouter } from "#server/modules/energy-tax/index.js";

export function mountUserApplicationApiRoutes(app: Express): void {
  app.use("/api/auth", authRouter);
  app.use("/api/faucet", faucetRouter);
  app.use("/api/wallet", walletRouter);
  app.use("/api/mining", miningRouter);
  app.use("/api/shop", shopRouter);
  app.use("/api/inventory", inventoryRouter);
  app.use("/api/machines", machinesRouter);
  app.use("/api/racks", racksRouter);
  app.use("/api/vault", vaultRouter);
  app.use("/api/read-earn", readEarnRouter);
  app.use("/api/rooms", roomsRouter);
  app.use("/api/checkin", checkinRouter);
  app.use("/api/offer-events", offerEventsRouter);
  app.use("/api/mini-pass", miniPassRouter);
  app.use("/api/daily-tasks", dailyTasksRouter);
  app.use("/api/internal-offerwall", internalOfferwallRouter);
  app.use("/api/chat", chatRouter);
  app.use("/api/ranking", rankingRouter);
  app.use("/api/stats", statsRouter);
  app.use("/api/shortlink", shortlinkRouter);
  app.use("/api/youtube", youtubeRouter);
  app.use("/api/games", gamesRouter);
  app.use("/api/auto-mining-gpu", autoMiningGpuRouter);
  app.use("/api/session", sessionRouter);
  app.use("/api/notifications", notificationRouter);
  app.use("/api/broadcast", broadcastRouter);
  app.use("/api/swap", swapRouter);
  app.use("/api/support", supportRouter);
  app.use("/api/user", userRouter);
  app.use("/api/sidebar", sidebarNavRouter);
  app.use("/api/reward-inbox", rewardInboxRouter);
  app.use("/api/public-support", publicSupportRouter);
  app.use("/api/zerads", zeradsRouter);
  app.use("/api/power-boost", powerBoostRouter);
  app.use("/api/social", socialRouter);
  app.use("/api/tournaments", tournamentsRouter);
  app.use("/api/ptc", ptcRouter);
  app.use("/api/partner-games", partnerGamesRouter);
  app.use("/api/burn-events", burnEventsRouter);
  app.use("/api/energy-tax", energyTaxRouter);
}
