/** Portuguese (pt-BR) landing copy */
export const landingPt = {
  meta: {
    title: "BlockMiner — Minere POL, jogue, ganhe recompensas | blockminer.space",
    description:
      "Jogo de mineração Web3 grátis na Polygon: monte sua fazenda, aumente o hashrate, jogue mini-jogos, check-in diário e ganhe POL real. Comunidade ativa. Não é aconselhamento financeiro.",
  },
  skip: "Pular para o conteúdo principal",
  nav: {
    login: "Entrar",
    register: "Criar conta",
    brand_aria: "Block Miner — início",
    language_group: "Idioma",
  },
  hero: {
    badge: "Jogo online — blocos sendo minerados agora",
    headline_line1: "Jogue, Minere e",
    headline_highlight: "Ganhe Cripto",
    headline_line2: "de Verdade",
    subheadline_before:
      "O jogo de mineração onde você monta sua farm, compra máquinas e ganha ",
    subheadline_emphasis: "criptomoedas reais",
    subheadline_after: " a cada bloco.",
    cta_primary: "Jogar Agora — É Grátis",
    cta_secondary: "Já tenho conta",
    trust_miners: "Mineradores ativos",
    trust_paid: "POL sacado on-chain",
    trust_rating: "Feito para jogadores no mundo todo",
    trust_stars_aria: "Cinco de cinco estrelas",
    visual_caption: "Fazenda simulada — seu painel após o cadastro",
  },
  stats: {
    users_label: "Jogadores cadastrados",
    users_sub: "e crescendo",
    withdrawn_label: "POL sacado",
    withdrawn_sub: "total de pagamentos on-chain",
    uptime_label: "No ar há",
    uptime_value: "{{count}} dias",
    uptime_sub: "desde 5 de março de 2026",
    miners_label: "Rigs online",
    miners_sub: "ativos no jogo agora",
    network_label: "Hashrate estimada da rede",
    network_sub: "Ilustrativo — escala com jogadores ativos",
    activity_label: "Sessões de jogo",
    activity_value: "1M+",
    activity_sub: "Mini-jogos e tarefas concluídas (acumulado)",
  },
  how: {
    kicker: "Como funciona",
    title: "Comece a minerar em três passos",
    subtitle: "Do zero ao hashrate em minutos.",
    step1_title: "Crie sua conta",
    step1_body: "Cadastre-se grátis em menos de um minuto. Sem cartão — seu painel fica pronto na hora.",
    step2_title: "Aumente o poder de mineração",
    step2_body: "Compre rigs na Loja, jogue para boosts temporários, faça check-in diário e complete faucet e shortlinks.",
    step3_title: "Ganhe e saque",
    step3_body: "Recompensas estilo POL seguem sua fatia do motor de blocos ao vivo. Saque na carteira ao atingir o mínimo.",
  },
  features: {
    kicker: "Por que o BlockMiner",
    title: "Por que os jogadores escolhem a gente",
    subtitle: "Rodadas reais no servidor, estatísticas transparentes e mais do que cliques passivos.",
    f1_title: "Sem investimento para começar",
    f1_body: "Jogue grátis. Ganhe saldo e hashrate com jogos, check-ins e tarefas — compras na loja usam só POL do jogo.",
    f2_title: "POL na Polygon",
    f2_body: "A economia é focada em Polygon (POL). Conecte sua carteira quando quiser depósitos e saques.",
    f3_title: "Jogue e ganhe poder",
    f3_body: "Memory Sync e Power Match dão hashrate temporário — pausas divertidas que mudam suas recompensas.",
    f4_title: "Recompensas diárias",
    f4_body: "Check-in, faucet, YouTube e GPU Auto Mining mantêm a progressão fresca todos os dias.",
    f5_title: "Indicações e comunidade",
    f5_body: "Convide amigos com seu link e cresça a rede — compartilhe recompensas conforme a equipe evolui.",
    f6_title: "Saque no seu ritmo",
    f6_body: "Peça saques on-chain ao passar os mínimos da plataforma. O processamento segue as regras da carteira.",
  },
  calculator: {
    title: "Calcule ganhos potenciais em POL",
    subtitle: "Usa o mesmo modelo de recompensa do calculador público (0,15 POL por bloco, ~10 min). O tamanho da rede é estimado com dados ao vivo.",
    slider_label: "Seu poder de mineração (H/s)",
    network_note: "Rede estimada: escala com rigs ativos na plataforma.",
    per_day: "Por dia (est.)",
    per_week: "Por semana (est.)",
    per_month: "Por mês (est.)",
    usd_note: "USD é ilustrativo (preço exemplo de POL). Não é cotação.",
    disclaimer:
      "Apenas estimativas. Recompensas reais dependem de hashrate da rede, rodadas e regras. Não é aconselhamento financeiro.",
    cta: "Começar com esse poder — criar conta",
  },
  community: {
    title: "Entre na nossa comunidade em crescimento",
    subtitle: "Os números vêm do servidor de jogo ao vivo.",
  },
  testimonials: {
    title: "O que os mineradores dizem",
    disclaimer: "Depoimentos ilustrativos para marketing; experiências variam.",
    t1_name: "João S.",
    t1_loc: "Brasil",
    t1_text:
      "Uso o BlockMiner entre as aulas — check-in e jogos somam. Saquei POL na MetaMask sem dor de cabeça.",
    t2_name: "María G.",
    t2_loc: "Espanha",
    t2_text:
      "Finalmente um jogo de mineração que explica hashrate e blocos. A página de transparência me convenceu; o Discord é ativo.",
    t3_name: "Jordan T.",
    t3_loc: "EUA",
    t3_text:
      "Vibe RollerCoin, mas na Polygon. Menos ruído, fluxo de carteira mais claro — jogo Memory Sync todo dia.",
  },
  games: {
    title: "Jogue, ganhe poder de mineração",
    subtitle: "Entre para rodar sessões — poderes são temporários e somam com seus rigs.",
    g1_name: "Memory Sync",
    g1_desc: "Combine peças rápido — o servidor concede boosts de hashrate por tempo.",
    g2_name: "Power Match",
    g2_desc: "Encadeie combos no tabuleiro para pontuações e recompensas maiores.",
    g3_name: "YouTube e Auto Mining",
    g3_desc: "Assista vídeos aprovados e sessões de GPU temporárias para mais H/s.",
    cta: "Jogar agora",
    login_hint: "Requer conta",
    view_all: "Ver todos os jogos",
  },
  crypto: {
    title: "Saque em POL na Polygon",
    subtitle: "Ativo principal hoje é POL (Polygon). Mais ativos podem chegar depois.",
    more: "Mais redes e tokens podem ser adicionados — acompanhe os anúncios.",
    soon: "em breve",
  },
  faq: {
    title: "FAQ",
    heading: "Perguntas frequentes",
    q1: "O BlockMiner é realmente grátis?",
    a1:
      "Sim. Você pode se cadastrar, jogar e ganhar sem gastar fiat. Compras na loja e alguns fluxos usam POL do jogo que você ganhou ou depositou.",
    q2: "Como faço o saque?",
    a2:
      "Conecte uma carteira Polygon, atinja o mínimo mostrado na página Carteira e envie o pedido. O tempo depende da fila de revisão — muitas vezes em até 72 horas úteis em fluxos manuais.",
    q3: "O que é poder de mineração (H/s)?",
    a3:
      "Hashrate define sua fatia de cada rodada de bloco simulada. Mais H/s em relação à rede significa maior parte do pool de recompensa da rodada.",
    q4: "Posso ganhar sem mini-jogos?",
    a4:
      "Sim — rigs, check-in, faucet, shortlinks, indicações, YouTube e Auto Mining contribuem. Jogas são boosts opcionais.",
    q5: "Meus dados estão seguros?",
    a5:
      "Usamos práticas padrão para auth e APIs. Nunca compartilhe sua seed phrase. Para direitos de privacidade (LGPD/GDPR), fale com o suporte pelos canais oficiais.",
  },
  final_cta: {
    title: "Pronto para começar a minerar?",
    subtitle: "Junte-se a milhares de jogadores ganhando recompensas estilo POL — sem cartão de crédito.",
    primary: "Criar conta grátis",
    bullet1: "Sem cartão de crédito",
    bullet2: "Grátis para começar",
    bullet3: "Saque ao atingir os mínimos",
  },
  closing: {
    kicker: "Comece hoje",
    title: "Sua fazenda está a um cadastro de distância.",
    body: "Crie uma conta, explore o painel e conecte uma carteira quando quiser fluxos on-chain reais.",
    register: "Criar conta grátis",
    login: "Já tenho conta",
  },
  footer: {
    tagline: "Minere crypto. Jogue. Ganhe recompensas.",
    disclaimer: "Simulação Web3 educativa — crypto envolve risco; não é aconselhamento financeiro.",
    copyright: "© {{year}} Block Miner. Todos os direitos reservados.",
    col_product: "Produto",
    link_how: "Como funciona",
    link_games: "Jogos",
    link_calc: "Calculadora",
    link_transparency: "Transparência",
    col_company: "Recursos",
    link_roadmap: "Roadmap",
    link_manual: "Manual / ajuda",
    col_legal: "Legal e segurança",
    link_terms: "Termos e políticas (manual)",
    link_privacy: "Transparência e custos",
    social_discord: "Discord",
    social_telegram: "Telegram",
    social_twitter: "X",
    social_youtube: "YouTube",
    theme_aria: "Tema de cores",
    theme_light: "Claro",
    theme_dark: "Escuro",
  },
};
