/** English landing copy — merged into en.json by merge-landing-locales.mjs */
export const landingEn = {
  meta: {
    title: "BlockMiner — Mine POL, Play Games, Earn Rewards | blockminer.space",
    description:
      "Free Web3 mining game on Polygon: build your farm, grow hashrate, play mini-games, daily check-ins, and earn real POL. Join a live community. Not financial advice.",
  },
  skip: "Skip to main content",
  nav: {
    login: "Sign in",
    register: "Create account",
    brand_aria: "Block Miner home",
    language_group: "Language",
  },
  hero: {
    badge: "Game online — blocks mining now",
    headline_line1: "Play, Mine &",
    headline_highlight: "Earn Real Crypto",
    headline_line2: "For Real",
    subheadline_before:
      "The mining game where you build your farm, buy machines, and earn ",
    subheadline_emphasis: "real cryptocurrencies",
    subheadline_after: " every block.",
    cta_primary: "Play now — it's free",
    cta_secondary: "I already have an account",
    trust_miners: "Active miners",
    trust_paid: "POL withdrawn on-chain",
    trust_rating: "Built for players worldwide",
    trust_stars_aria: "Five out of five stars",
    visual_caption: "Simulated mining farm — your dashboard after signup",
  },
  stats: {
    users_label: "Registered players",
    users_sub: "and growing",
    withdrawn_label: "POL withdrawn",
    withdrawn_sub: "total on-chain payouts",
    uptime_label: "Live for",
    uptime_value: "{{count}} days",
    uptime_sub: "since March 5, 2026",
    miners_label: "Rigs online",
    miners_sub: "active in-game now",
    network_label: "Est. network hashrate",
    network_sub: "Illustrative — scales with active players",
    activity_label: "Game sessions",
    activity_value: "1M+",
    activity_sub: "Mini-games & tasks completed (cumulative)",
  },
  how: {
    kicker: "How it works",
    title: "Start mining in three simple steps",
    subtitle: "From zero to hashrate in minutes.",
    step1_title: "Create your account",
    step1_body: "Sign up free in under a minute. No credit card — your dashboard is ready instantly.",
    step2_title: "Grow mining power",
    step2_body: "Buy rigs in the Shop, play games for temporary boosts, check in daily, and complete faucet & shortlink tasks.",
    step3_title: "Earn & withdraw",
    step3_body: "POL-style rewards follow your share of the live block engine. Withdraw to your wallet when you meet the minimum.",
  },
  features: {
    kicker: "Why BlockMiner",
    title: "Why players choose us",
    subtitle: "Real server-side rounds, transparent stats, and more than passive clicking.",
    f1_title: "No investment to start",
    f1_body: "Play for free. Earn balance and hashrate through gameplay, check-ins, and tasks — optional shop purchases use in-game POL only.",
    f2_title: "POL on Polygon",
    f2_body: "The economy is wired for Polygon (POL). Link your wallet when you are ready for deposits and withdrawals.",
    f3_title: "Play & earn power",
    f3_body: "Memory Sync and Power Match grant temporary hashrate — fun breaks that actually move your rewards.",
    f4_title: "Daily rewards",
    f4_body: "Check in, faucet, YouTube rewards, and Auto Mining GPU keep progression fresh every day.",
    f5_title: "Referrals & community",
    f5_body: "Invite friends with your link and grow the network — share rewards as your crew levels up.",
    f6_title: "Withdraw on your terms",
    f6_body: "Request on-chain withdrawals when you pass platform minimums. Processing follows our wallet rules.",
  },
  calculator: {
    title: "Calculate potential POL earnings",
    subtitle: "Uses the same block reward model as our public calculator (0.15 POL per block, ~10 min). Network size is estimated from live player data.",
    slider_label: "Your mining power (H/s)",
    network_note: "Estimated network: scales with active rigs on the platform.",
    per_day: "Per day (est.)",
    per_week: "Per week (est.)",
    per_month: "Per month (est.)",
    usd_note: "USD is illustrative (example POL price). Not a quote.",
    disclaimer:
      "Estimates only. Actual rewards depend on network hashrate, rounds, and rules. Not financial advice.",
    cta: "Start with this power — create account",
  },
  community: {
    title: "Join our growing community",
    subtitle: "Numbers update from the live game server.",
  },
  testimonials: {
    title: "What miners say",
    disclaimer: "Illustrative quotes for marketing; experiences vary.",
    t1_name: "João S.",
    t1_loc: "Brazil",
    t1_text:
      "I use BlockMiner between classes — the check-in and games actually add up. Withdrew POL to MetaMask without drama.",
    t2_name: "María G.",
    t2_loc: "Spain",
    t2_text:
      "Finally a mining game that explains hashrate and blocks. Transparency page sold me; the Discord is active too.",
    t3_name: "Jordan T.",
    t3_loc: "USA",
    t3_text:
      "RollerCoin vibes but on Polygon. Lower noise, clearer wallet flow — I play Memory Sync daily.",
  },
  games: {
    title: "Play games, earn mining power",
    subtitle: "Log in to run sessions — powers are temporary and stack with your rigs.",
    g1_name: "Memory Sync",
    g1_desc: "Match crypto tiles fast — server grants timed hashrate boosts.",
    g2_name: "Power Match",
    g2_desc: "Chain combos on the board for bigger scores and rewards.",
    g3_name: "YouTube & Auto Mining",
    g3_desc: "Watch approved videos and timed GPU sessions for extra H/s.",
    cta: "Play now",
    login_hint: "Requires account",
    view_all: "View all games",
  },
  crypto: {
    title: "Withdraw in POL on Polygon",
    subtitle: "Primary asset today is POL (Polygon). More assets may arrive later.",
    more: "More networks & tokens may be added — follow announcements.",
    soon: "soon",
  },
  faq: {
    title: "FAQ",
    heading: "Frequently asked questions",
    q1: "Is BlockMiner really free?",
    a1:
      "Yes. You can register, play, and earn without spending fiat. Shop purchases and some flows use in-game POL you earned or deposited.",
    q2: "How do I withdraw?",
    a2:
      "Link a Polygon wallet, reach the minimum withdrawal shown in the Wallet page, and submit a request. Processing time depends on review load — often within 72 business hours for manual pipelines.",
    q3: "What is mining power (H/s)?",
    a3:
      "Hashrate decides your share of each simulated block round. More H/s versus the network means a larger slice of the round reward pool.",
    q4: "Can I earn without mini-games?",
    a4:
      "Yes — rigs, check-ins, faucet, shortlinks, referrals, YouTube, and Auto Mining all contribute. Games are optional boosts.",
    q5: "Is my data secure?",
    a5:
      "We use industry-standard practices for auth and APIs. Never share your seed phrase. For privacy rights (LGPD/GDPR), contact support through official channels.",
  },
  final_cta: {
    title: "Ready to start mining?",
    subtitle: "Join thousands of players earning POL-style rewards — no credit card required.",
    primary: "Create free account",
    bullet1: "No credit card required",
    bullet2: "Free to start",
    bullet3: "Withdraw when you meet minimums",
  },
  closing: {
    kicker: "Start today",
    title: "Your farm is one signup away.",
    body: "Create an account, explore the dashboard, and connect a wallet whenever you want real on-chain flows.",
    register: "Create free account",
    login: "I already have an account",
  },
  footer: {
    tagline: "Mine crypto. Play games. Earn rewards.",
    disclaimer: "Educational Web3 simulation — crypto involves risk; not financial advice.",
    copyright: "© {{year}} Block Miner. All rights reserved.",
    col_product: "Product",
    link_how: "How it works",
    link_games: "Games",
    link_calc: "Calculator",
    link_transparency: "Transparency",
    col_company: "Resources",
    link_roadmap: "Roadmap",
    link_manual: "Manual / help",
    col_legal: "Legal & safety",
    link_terms: "Terms & policies (manual)",
    link_privacy: "Transparency & costs",
    social_discord: "Discord",
    social_telegram: "Telegram",
    social_twitter: "X",
    social_youtube: "YouTube",
    theme_aria: "Color theme",
    theme_light: "Light",
    theme_dark: "Dark",
  },
};
