/** Spanish landing copy */
export const landingEs = {
  meta: {
    title: "BlockMiner — Mina POL, juega, gana recompensas | blockminer.space",
    description:
      "Juego de minería Web3 gratis en Polygon: construye tu granja, sube el hashrate, mini-juegos, check-in diario y gana POL real. Comunidad activa. No es asesoramiento financiero.",
  },
  skip: "Saltar al contenido principal",
  nav: {
    login: "Iniciar sesión",
    register: "Crear cuenta",
    brand_aria: "Block Miner — inicio",
    language_group: "Idioma",
  },
  hero: {
    badge: "Juego online — bloques minándose ahora",
    headline_line1: "Juega, mina y",
    headline_highlight: "Gana cripto",
    headline_line2: "de verdad",
    subheadline_before:
      "El juego de minería donde montas tu granja, compras máquinas y ganas ",
    subheadline_emphasis: "criptomonedas reales",
    subheadline_after: " en cada bloque.",
    cta_primary: "Jugar ahora — es gratis",
    cta_secondary: "Ya tengo cuenta",
    trust_miners: "Mineros activos",
    trust_paid: "POL retirado on-chain",
    trust_rating: "Hecho para jugadores de todo el mundo",
    trust_stars_aria: "Cinco de cinco estrellas",
    visual_caption: "Granja simulada — tu panel tras registrarte",
  },
  stats: {
    users_label: "Jugadores registrados",
    users_sub: "y creciendo",
    withdrawn_label: "POL retirado",
    withdrawn_sub: "total de pagos on-chain",
    uptime_label: "En línea durante",
    uptime_value: "{{count}} días",
    uptime_sub: "desde el 5 de marzo de 2026",
    miners_label: "Rigs en línea",
    miners_sub: "activos en el juego ahora",
    network_label: "Hashrate de red estimado",
    network_sub: "Ilustrativo — escala con jugadores activos",
    activity_label: "Sesiones de juego",
    activity_value: "1M+",
    activity_sub: "Mini-juegos y tareas completadas (acumulado)",
  },
  how: {
    kicker: "Cómo funciona",
    title: "Empieza a minar en tres pasos",
    subtitle: "De cero a hashrate en minutos.",
    step1_title: "Crea tu cuenta",
    step1_body: "Regístrate gratis en menos de un minuto. Sin tarjeta — tu panel queda listo al instante.",
    step2_title: "Aumenta el poder de minería",
    step2_body: "Compra rigs en la Tienda, juega para boosts temporales, haz check-in diario y completa faucet y shortlinks.",
    step3_title: "Gana y retira",
    step3_body: "Las recompensas estilo POL siguen tu parte del motor de bloques en vivo. Retira a tu wallet al alcanzar el mínimo.",
  },
  features: {
    kicker: "Por qué BlockMiner",
    title: "Por qué nos eligen los jugadores",
    subtitle: "Rondas reales en servidor, stats transparentes y más que clics pasivos.",
    f1_title: "Sin inversión para empezar",
    f1_body: "Juega gratis. Gana saldo y hashrate con juegos, check-ins y tareas — la tienda usa solo POL del juego.",
    f2_title: "POL en Polygon",
    f2_body: "La economía está orientada a Polygon (POL). Conecta tu wallet cuando quieras depósitos y retiros.",
    f3_title: "Juega y gana poder",
    f3_body: "Memory Sync y Power Match dan hashrate temporal — descansos divertidos que mueven tus recompensas.",
    f4_title: "Recompensas diarias",
    f4_body: "Check-in, faucet, YouTube y GPU Auto Mining mantienen la progresión fresca cada día.",
    f5_title: "Referidos y comunidad",
    f5_body: "Invita amigos con tu link y crece la red — comparte recompensas mientras sube el equipo.",
    f6_title: "Retiros a tu ritmo",
    f6_body: "Solicita retiros on-chain al superar los mínimos de la plataforma. El procesamiento sigue las reglas de wallet.",
  },
  calculator: {
    title: "Calcula ganancias potenciales en POL",
    subtitle: "Usa el mismo modelo de recompensa que la calculadora pública (0,15 POL por bloque, ~10 min). El tamaño de red se estima con datos en vivo.",
    slider_label: "Tu poder de minería (H/s)",
    network_note: "Red estimada: escala con rigs activos en la plataforma.",
    per_day: "Por día (est.)",
    per_week: "Por semana (est.)",
    per_month: "Por mes (est.)",
    usd_note: "USD es ilustrativo (precio ejemplo de POL). No es cotización.",
    disclaimer:
      "Solo estimaciones. Las recompensas reales dependen del hashrate de la red, rondas y reglas. No es asesoramiento financiero.",
    cta: "Empezar con este poder — crear cuenta",
  },
  community: {
    title: "Únete a nuestra comunidad en crecimiento",
    subtitle: "Los números vienen del servidor de juego en vivo.",
  },
  testimonials: {
    title: "Lo que dicen los mineros",
    disclaimer: "Testimonios ilustrativos de marketing; las experiencias varían.",
    t1_name: "João S.",
    t1_loc: "Brasil",
    t1_text:
      "Uso BlockMiner entre clases — el check-in y los juegos suman. Retiré POL a MetaMask sin problemas.",
    t2_name: "María G.",
    t2_loc: "España",
    t2_text:
      "Por fin un juego de minería que explica hashrate y bloques. La página de transparencia me convenció; Discord activo.",
    t3_name: "Jordan T.",
    t3_loc: "EE. UU.",
    t3_text:
      "Vibes RollerCoin pero en Polygon. Menos ruido, flujo de wallet más claro — juego Memory Sync a diario.",
  },
  games: {
    title: "Juega, gana poder de minería",
    subtitle: "Inicia sesión para sesiones — los poderes son temporarios y suman con tus rigs.",
    g1_name: "Memory Sync",
    g1_desc: "Empareja fichas rápido — el servidor otorga boosts de hashrate por tiempo.",
    g2_name: "Power Match",
    g2_desc: "Encadena combos en el tablero para puntuaciones y recompensas mayores.",
    g3_name: "YouTube y Auto Mining",
    g3_desc: "Videos aprobados y sesiones GPU temporales para más H/s.",
    cta: "Jugar ahora",
    login_hint: "Requiere cuenta",
    view_all: "Ver todos los juegos",
  },
  crypto: {
    title: "Retira en POL en Polygon",
    subtitle: "El activo principal hoy es POL (Polygon). Más activos pueden llegar después.",
    more: "Más redes y tokens pueden añadirse — sigue los anuncios.",
    soon: "pronto",
  },
  faq: {
    title: "FAQ",
    heading: "Preguntas frecuentes",
    q1: "¿BlockMiner es realmente gratis?",
    a1:
      "Sí. Puedes registrarte, jugar y ganar sin gastar fiat. Compras en la tienda y algunos flujos usan POL del juego que ganaste o depositaste.",
    q2: "¿Cómo retiro?",
    a2:
      "Conecta una wallet Polygon, alcanza el mínimo mostrado en Wallet y envía la solicitud. El tiempo depende de la cola de revisión — a menudo en 72 h hábiles en flujos manuales.",
    q3: "¿Qué es el poder de minería (H/s)?",
    a3:
      "El hashrate define tu parte de cada ronda de bloque simulada. Más H/s frente a la red significa mayor parte del pool de recompensa.",
    q4: "¿Puedo ganar sin mini-juegos?",
    a4:
      "Sí — rigs, check-in, faucet, shortlinks, referidos, YouTube y Auto Mining contribuyen. Los juegos son boosts opcionales.",
    q5: "¿Mis datos están seguros?",
    a5:
      "Usamos prácticas estándar para auth y APIs. Nunca compartas tu frase semilla. Para derechos de privacidad (LGPD/GDPR), contacta soporte por canales oficiales.",
  },
  final_cta: {
    title: "¿Listo para empezar a minar?",
    subtitle: "Únete a miles de jugadores ganando recompensas estilo POL — sin tarjeta de crédito.",
    primary: "Crear cuenta gratis",
    bullet1: "Sin tarjeta de crédito",
    bullet2: "Gratis para empezar",
    bullet3: "Retira al cumplir los mínimos",
  },
  closing: {
    kicker: "Empieza hoy",
    title: "Tu granja está a un registro de distancia.",
    body: "Crea una cuenta, explora el panel y conecta una wallet cuando quieras flujos on-chain reales.",
    register: "Crear cuenta gratis",
    login: "Ya tengo cuenta",
  },
  footer: {
    tagline: "Mina crypto. Juega. Gana recompensas.",
    disclaimer: "Simulación Web3 educativa — el crypto implica riesgo; no es asesoramiento financiero.",
    copyright: "© {{year}} Block Miner. Todos los derechos reservados.",
    col_product: "Producto",
    link_how: "Cómo funciona",
    link_games: "Juegos",
    link_calc: "Calculadora",
    link_transparency: "Transparencia",
    col_company: "Recursos",
    link_roadmap: "Roadmap",
    link_manual: "Manual / ayuda",
    col_legal: "Legal y seguridad",
    link_terms: "Términos y políticas (manual)",
    link_privacy: "Transparencia y costes",
    social_discord: "Discord",
    social_telegram: "Telegram",
    social_twitter: "X",
    social_youtube: "YouTube",
    theme_aria: "Tema de colores",
    theme_light: "Claro",
    theme_dark: "Oscuro",
  },
};
