export const FAUCET_ERROR = {
  UNAUTHENTICATED: "FAUCET_UNAUTHENTICATED",
  COOLDOWN_ACTIVE: "FAUCET_COOLDOWN_ACTIVE",
  CLAIM_NOT_AVAILABLE: "FAUCET_CLAIM_NOT_AVAILABLE",
  PARTNER_INCOMPLETE: "FAUCET_PARTNER_INCOMPLETE",
  REWARD_NOT_CONFIGURED: "FAUCET_REWARD_NOT_CONFIGURED",
  INTERNAL: "FAUCET_INTERNAL_ERROR",
} as const;

export type FaucetErrorCode = (typeof FAUCET_ERROR)[keyof typeof FAUCET_ERROR];
