ALTER TYPE "TournamentMetric" ADD VALUE IF NOT EXISTS 'OFFERS_INTERNAL';
ALTER TYPE "TournamentMetric" ADD VALUE IF NOT EXISTS 'OFFERS_EXTERNAL';
ALTER TYPE "TournamentMetric" ADD VALUE IF NOT EXISTS 'OFFERS_ALL';
