export const AUTO_MINING_ERROR = {
  GPU_NOT_FOUND: "GPU_NOT_FOUND",
  DAILY_LIMIT_REACHED: "DAILY_LIMIT_REACHED",
  INSUFFICIENT_SECONDS: "INSUFFICIENT_SECONDS",
  GPU_ID_REQUIRED: "GPU_ID_REQUIRED",

  NO_SESSION: "NO_SESSION",
  WRONG_MODE: "WRONG_MODE",
  CLAIM_NOT_DUE: "CLAIM_NOT_DUE",
  DAILY_LIMIT: "DAILY_LIMIT",
  CONCURRENT_CLAIM: "CONCURRENT_CLAIM",
  INVALID_MODE: "INVALID_MODE",
  NOT_FOUND: "NOT_FOUND",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  NOT_CLICKED: "NOT_CLICKED",
  CLICK_TOO_FAST: "CLICK_TOO_FAST",
  IMPRESSION_EXPIRED: "IMPRESSION_EXPIRED",
  SCHEMA_UNAVAILABLE: "SCHEMA_UNAVAILABLE",
  VALIDATION: "VALIDATION",
  SERVER_ERROR: "SERVER_ERROR",
} as const;

export type AutoMiningErrorCode = (typeof AUTO_MINING_ERROR)[keyof typeof AUTO_MINING_ERROR];
