export const WALLET_ERROR = {
  INVALID_ADDRESS: "WALLET_INVALID_ADDRESS",
  INVALID_CHAIN: "WALLET_INVALID_CHAIN",
  CHALLENGE_NOT_FOUND: "WALLET_CHALLENGE_NOT_FOUND",
  CHALLENGE_EXPIRED: "WALLET_CHALLENGE_EXPIRED",
  INVALID_SIGNATURE: "WALLET_INVALID_SIGNATURE",
  UNAUTHENTICATED: "WALLET_UNAUTHENTICATED",
} as const;
