export const YOUTUBE_ERROR = {
  INSUFFICIENT_BALANCE: "YOUTUBE_INSUFFICIENT_BALANCE",
  DAILY_LIMIT_REACHED: "YOUTUBE_DAILY_LIMIT_REACHED",
  INTERNAL: "YOUTUBE_INTERNAL_ERROR",
} as const;

export type YoutubeErrorCode = (typeof YOUTUBE_ERROR)[keyof typeof YOUTUBE_ERROR];
