export const VAULT_ERROR = {
  NOT_FOUND: "NOT_FOUND",
  ALREADY_STORED: "VAULT_ALREADY_STORED",
  INVALID_SLOT: "INVALID_SLOT",
  BAD_SOURCE: "VAULT_BAD_SOURCE",
  BAD_DESTINATION: "VAULT_BAD_DESTINATION",
  UNAVAILABLE: "VAULT_UNAVAILABLE",
  RACK_LINK: "VAULT_RACK_LINK",
  RETRIEVE_ERROR: "VAULT_RETRIEVE_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type VaultErrorCode = (typeof VAULT_ERROR)[keyof typeof VAULT_ERROR];
