#!/usr/bin/env bash
# Run on the BlockMiner VPS as root (same machine as docker compose nginx on 80/443).
# Publishes BTCPay nginx on host ports 39180 (HTTP) and 39443 (HTTPS); BlockMiner nginx proxies btcpay.blockminer.space.
# Requires: repo at expected path, docker compose profile proxy, DNS A for btcpay.blockminer.space → this host.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BT_DIR="${REPO_ROOT}/docker/btcpay"
ENV_DEST="${BT_DIR}/env"
LE_EMAIL="${BTCPAY_LE_EMAIL:-admin@blockminer.com}"

mkdir -p "${REPO_ROOT}/nginx/certs-btcpay" "${REPO_ROOT}/certbot-www"

echo "==> Writing ${ENV_DEST} (coexistence ports 39180 / 39443)"
cat >"${ENV_DEST}" <<EOF
# Generated by scripts/vps-btcpay-coexist-install.sh — do not commit (gitignored as docker/btcpay/env)
BTCPAY_HOST=btcpay.blockminer.space
LETSENCRYPT_EMAIL=${LE_EMAIL}
NBITCOIN_NETWORK=testnet
BTCPAYGEN_CRYPTO1=btc
BTCPAYGEN_REVERSEPROXY=nginx
BTCPAYGEN_LIGHTNING=clightning
BTCPAYGEN_ADDITIONAL_FRAGMENTS=opt-save-storage-s
BTCPAY_ENABLE_SSH=false
BTCPAY_ADDITIONAL_HOSTS=
REVERSEPROXY_HTTP_PORT=39180
REVERSEPROXY_HTTPS_PORT=39443
BTCPAY_INSTALL_DIR=${BT_DIR}/btcpayserver-docker
EOF

echo "==> Reload BlockMiner nginx (TLS bootstrap + btcpay reverse-proxy in nginx.conf)"
cd "${REPO_ROOT}"
if [[ -f .env.production ]]; then
  export COMPOSE_PROFILES=proxy
  docker compose --env-file .env.production stop nginx 2>/dev/null || true
  docker compose --env-file .env.production rm -f nginx 2>/dev/null || true
  docker compose --env-file .env.production up -d nginx
else
  echo "WARNING: missing .env.production — start nginx manually with COMPOSE_PROFILES=proxy"
fi

echo "==> Starting BTCPay official install in background (sync can take hours)..."
LOG_FILE=/root/btcpay-blockminer-install.log
if [[ -f "${BT_DIR}/install-btcpay.sh" ]]; then
  (
    cd "${BT_DIR}"
    nohup bash ./install-btcpay.sh >>"${LOG_FILE}" 2>&1
  ) &
  echo "BTCPay install PID=$! — tail -f ${LOG_FILE}"
else
  echo "ERROR: ${BT_DIR}/install-btcpay.sh not found"
  exit 1
fi
