export const AuditEventStatus = {
  SUCCESS: "SUCCESS",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED"
};

export const AuditEventType = {
  AUTH_REGISTER: "AUTH_REGISTER",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_REFRESH_TOKEN: "AUTH_REFRESH_TOKEN",
  AUTH_PASSWORD_CHANGE: "AUTH_PASSWORD_CHANGE",
  AUTH_FORCED_LOGOUT: "AUTH_FORCED_LOGOUT",
  AUTH_2FA_CHALLENGE: "AUTH_2FA_CHALLENGE",
  AUTH_2FA_SUCCESS: "AUTH_2FA_SUCCESS",
  AUTH_2FA_FAILURE: "AUTH_2FA_FAILURE",
  USER_VIDEO_START: "USER_VIDEO_START",
  USER_VIDEO_PROGRESS: "USER_VIDEO_PROGRESS",
  USER_VIDEO_COMPLETE: "USER_VIDEO_COMPLETE",
  USER_VIDEO_ERROR: "USER_VIDEO_ERROR",
  USER_NAVIGATION: "USER_NAVIGATION",
  USER_CLICK_CRITICAL: "USER_CLICK_CRITICAL",
  USER_SESSION_DURATION: "USER_SESSION_DURATION",
  ECONOMY_CLAIM_FAUCET: "ECONOMY_CLAIM_FAUCET",
  ECONOMY_MACHINE_PURCHASE: "ECONOMY_MACHINE_PURCHASE",
  ECONOMY_MACHINE_SELL: "ECONOMY_MACHINE_SELL",
  ECONOMY_MACHINE_UPGRADE: "ECONOMY_MACHINE_UPGRADE",
  ECONOMY_DEPOSIT: "ECONOMY_DEPOSIT",
  ECONOMY_WITHDRAWAL: "ECONOMY_WITHDRAWAL",
  ECONOMY_INTERNAL_TRANSFER: "ECONOMY_INTERNAL_TRANSFER",
  ECONOMY_EXTERNAL_TRANSFER: "ECONOMY_EXTERNAL_TRANSFER",
  ECONOMY_STAKING: "ECONOMY_STAKING",
  ECONOMY_MINING_REWARD: "ECONOMY_MINING_REWARD",
  ECONOMY_TX_FAILURE: "ECONOMY_TX_FAILURE",
  ECONOMY_GAS_ESTIMATION: "ECONOMY_GAS_ESTIMATION",
  SYSTEM_ACCOUNT_CREATE: "SYSTEM_ACCOUNT_CREATE",
  SYSTEM_KYC_VERIFICATION: "SYSTEM_KYC_VERIFICATION",
  SYSTEM_PROFILE_UPDATE: "SYSTEM_PROFILE_UPDATE",
  SYSTEM_CRITICAL_ERROR: "SYSTEM_CRITICAL_ERROR",
  SYSTEM_HEALTHCHECK: "SYSTEM_HEALTHCHECK",
  SYSTEM_DEPLOY: "SYSTEM_DEPLOY",
  SYSTEM_ROLLBACK: "SYSTEM_ROLLBACK",
  SYSTEM_MAINTENANCE_MODE: "SYSTEM_MAINTENANCE_MODE"
};

export const AuditOutboxStatus = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
  DLQ: "DLQ"
};

export const AUDIT_SCHEMA_VERSION = "audit_event_v1";
export const AUDIT_SIGNATURE_ALGORITHM = "HMAC-SHA256";
export const AUDIT_MAX_OUTBOX_BATCH = 50;
export const AUDIT_DEFAULT_SOURCE = "api";
