export const ROOMS_ERROR = {
  NOT_FOUND: "ROOM_NOT_FOUND",
  RACK_NOT_FOUND: "RACK_NOT_FOUND",
  RACK_EMPTY: "RACK_EMPTY",
  RACK_OCCUPIED: "RACK_OCCUPIED",
  MAX_ROOMS: "MAX_ROOMS_REACHED",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  INVALID_PARAMS: "ROOM_INVALID_PARAMS",
  UNAUTHORIZED: "ROOM_UNAUTHENTICATED",
} as const;
